- src: https://github.com/jihedjarry/docker.git
  name: docker
  version: master
  scm: git

- src: https://github.com/jihedjarry/service-install-run_app2.git 
  name: service-install-run
  version: master
  scm: git

